server:
  port: 8090
  
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/Demo?autoreconnect=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  output :
    ansi:
      enabled: always