server:
  port: 8090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Demo?autoreconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update